name: Docker Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/arm64,linux/amd64
        push: true
        tags: us-central1-docker.pkg.dev/genuine-flight-317411/devel/krr:${{ github.ref }}
        build-args: |
          BUILDKIT_INLINE_CACHE=1
